version: '3.7'

services:
  app:
    build:
      context: ./
      # target: runtime
      args:
        REGISTRY: ${REGISTRY}
        MAVEN_SETTINGS_XML_URL: ${MAVEN_SETTINGS_XML_URL}
        NPM_CONFIG_REGISTRY: ${NPM_CONFIG_REGISTRY}
        SASS_BINARY_SITE: ${SASS_BINARY_SITE}
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://host.docker.internal;databaseName=shc_portal
      # SPRING_DATASOURCE_USERNAME: sa
      # SPRING_DATASOURCE_PASSWORD: Aa123456789

  db:
    image: nexus.elm.sa/mssql/server:2017-CU21-ubuntu-16.04
    # ports:
    #   - 1433:1433
    volumes:
      - "./src/main/sql/1.0.0:/data"
      - sqlserver-data:/home/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Aa123456789
      MSSQL_PID: Developer

volumes:
  sqlserver-data:
#
#    # MySQL database shared with tomcat containers.
#    db:
#      image: mysql:latest
#      environment:
#        MYSQL_ROOT_PASSWORD: Aa123456
#        MYSQL_DATABASE: dcc_quickstarts_aash
#        MYSQL_USER: dcc_quickstarts
#        MYSQL_PASSWORD: Aa123456
#      restart: always
#      command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
#      ports:
#            - "7706:3306"
#      volumes:
#        - "./src/main/sql/1.0.0/dcc-quickstarts-aash-create-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql"
#        - "./src/main/sql/1.0.0/dcc-quickstarts-aash-data.sql:/docker-entrypoint-initdb.d/2-data.sql"
#        - "./src/main/sql/1.2.0/dcc-quickstarts-aash-alter-schema.sql:/docker-entrypoint-initdb.d/3-schema.sql"
#        - "./src/main/sql/1.2.0/dcc-quickstarts-aash-data.sql:/docker-entrypoint-initdb.d/4-data.sql"
#        - "./src/main/sql/1.3.0/dcc-quickstarts-aash-alter-schema.sql:/docker-entrypoint-initdb.d/5-schema.sql"
#        - "./src/main/sql/1.3.0/dcc-quickstarts-aash-data.sql:/docker-entrypoint-initdb.d/6-data.sql"
#
#    # First node of the first Tomcat virtual host.
#    tomcat:
#      image: tomcat:9-jre8-alpine
#      # Environment variables do not appear to be getting loaded the first time Tomcat starts!
#      environment:
#        JDBC_URL: jdbc:mysql://db:3306/dcc_quickstarts_aash?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true;useSSL=false
#        JDBC_USER: dcc_quickstarts
#        JDBC_PASS: Aa123456
#      restart: always
#      ports:
#        - "8080"
#      volumes:
#        - "./dcc-quickstarts-aash-web/target:/usr/local/tomcat/webapps"
#      links:
#        - db
#
#
#    # nginx container that automatically creates a load balancer / reverse proxy across the 2 tomcat containers / 2 virtual hosts.
#    nginx:
#      image: jwilder/nginx-proxy:alpine
#      ports:
#        - "7080:7080"
#      volumes:
#        - "/var/run/docker.sock:/tmp/docker.sock:ro"
#        - "./nginx.conf:/etc/nginx/conf.d/my_nginx.conf"
#      restart: always
#      links:
#        - tomcat
