// `.env.ts` is generated by the `npm run env` command
import {env} from './.env';

export const environment = {
  production: true,
  dev: false,
  mock: false,
  recaptchaSiteKey: '6LdzHFQUAAAAAKbbaojHVswZvdHgPuzC71VCIUlb',
  invisibleRecaptchaSiteKey: '6Le30G0UAAAAAM3Kwdf4V_feWJ-zD7OFAjxqO3Vo',
  version: env.npm_package_version,
  backendMappings: [{mapping:'/core', url:'https://[STAG_URL]/shj-applicant/'}],
  websocketConnection: [{url: ''}],
  defaultLanguage: 'ar-SA',
  termsAndConditionsUrl: '',
  supportedLanguages: [
    'en-US',
    'ar-SA'
  ],
  mockData: [{}]
};
