// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import {env} from './.env';

export const environment = {
  production: false,
  dev: true,
  mock: false,
  recaptchaSiteKey: '6LdzHFQUAAAAAKbbaojHVswZvdHgPuzC71VCIUlb',
  invisibleRecaptchaSiteKey: '6Le30G0UAAAAAM3Kwdf4V_feWJ-zD7OFAjxqO3Vo',
  version: env.npm_package_version + '-dev',
  backendMappings: [{mapping:'/core', url:'http://localhost:8080/shj-applicant/'}],
  websocketConnection: [{url: ''}],
  defaultLanguage: 'ar-SA',
  termsAndConditionsUrl: '',
  supportedLanguages: [
    'en-US',
    'ar-SA'
  ],
  mockData: [
    {url: '/api/auth/login', data: '{"authorities":[],"details":null,"authenticated":false,"principal":"1234567897","credentials":null,"otpRequired":true,"firstName":"سعد","lastName":"الغامدي","email":"sg***@el****.sa","mobileNumber":"*******678","otpExpiryMinutes":5,"name":"1234567897"}'},
    {url: '/api/auth/otp', data: '{"authorities":[{"authority":"ROLE_MANAGEMENT"},{"authority":"ADD_USER"},{"authority":"EDIT_USER"},{"authority":"USER_MANAGEMENT"},{"authority":"CHANGE_ROLE_STATUS"},{"authority":"DELETE_ROLE"},{"authority":"CHANGE_USER_STATUS"},{"authority":"RESET_USER_PASSWORD"},{"authority":"EDIT_ROLE"},{"authority":"DELETE_USER"},{"authority":"RESET_PASSWORD"},{"authority":"ADD_ROLE"},{"authority":"ADMIN_DASHBOARD"}],"details":null,"authenticated":true,"principal":"1234567897","credentials":null,"token":null,"tokenExpirationDate":0,"passwordExpired":false,"userRoles":[{"id":1,"role":{"id":1,"nameArabic":"مشرف النظام","nameEnglish":"System Admin","deleted":false,"activated":true,"roleAuthorities":null,"creationDate":1616492160000,"updateDate":null},"mainRole":true,"creationDate":1616596260000}],"firstName":"سعد","lastName":"الغامدي","name":"1234567897"}'},
    {url: '/api/lookup/country/list', data:'[{"code":"EG","lang":"en","label":"Egypt"},{"code":"EG","lang":"ar","label":"\u0645\u0635\u0631"}]'},
    {url: '/api/lookup/marital-status/list', data:'[{"code":"SINGLE","lang":"en","label":"Single"},{"code":"SINGLE","lang":"ar","label":"\u0623\u0639\u0632\u0628"},{"code":"MARRIED","lang":"en","label":"Married"},{"code":"MARRIED","lang":"ar","label":"\u0645\u062a\u0632\u0648\u062c"}]'},
    {url: '/api/lookup/ritual-type/list', data:'[{"code":"INTERNAL_HAJJ","lang":"en","label":"Internal Hajj"},{"code":"INTERNAL_HAJJ","lang":"ar","label":"\u062d\u062c\u0627\u062c \u0627\u0644\u062f\u0627\u062e\u0644"},{"code":"EXTERNAL_HAJJ","lang":"en","label":"External Hajj"},{"code":"EXTERNAL_HAJJ","lang":"ar","label":"\u062d\u062c\u0627\u062c \u0627\u0644\u062e\u0627\u0631\u062c"}]'},
    {url: '/api/lookup/relative-relationship/list', data:'[{"code":"MOTHER","lang":"en","label":"Mother"},{"code":"MOTHER","lang":"ar","label":"\u0623\u0645"},{"code":"FATHER","lang":"en","label":"Father"},{"code":"FATHER","lang":"ar","label":"\u0623\u0628"}]'},

  ]
};
