// `.env.ts` is generated by the `npm run env` command
import {env} from './.env';

export const environment = {
  production: true,
  dev: false,
  mock: false,
  recaptchaSiteKey: '[PROD_KEY]',
  invisibleRecaptchaSiteKey: '[PROD_KEY]',
  version: env.npm_package_version,
  backendMappings: [{mapping:'/core', url:'https://[PROD_URL]/shj-applicant/'}],
  websocketConnection: [{url: ''}],
  defaultLanguage: 'ar-SA',
  termsAndConditionsUrl: '',
  supportedLanguages: [
    'en-US',
    'ar-SA'
  ],
  mockData: [{}]
};
