// `.env.ts` is generated by the `npm run env` command
import {env} from './.env';

export const environment = {
  production: true,
  dev: false,
  mock: false,
  recaptchaSiteKey: '6LeKPfsfAAAAAMVpDKiCul4Huulvobe-72cVqtQP',
  invisibleRecaptchaSiteKey: '6LcqP_sfAAAAADX0lVo04bIKnSn0_avnuxMq3hAN',
  version: env.npm_package_version,
  backendMappings: [{mapping:'/core', url:'https://stg-shp.haj.gov.sa/'}],
  websocketConnection: [{url: ''}],
  defaultLanguage: 'ar-SA',
  termsAndConditionsUrl: '',
  supportedLanguages: [
    'en-US',
    'ar-SA'
  ],
  mockData: [{}]
};
