USE MASTER
GO
CREATE LOGIN "sha_user" WITH PASSWORD=N'Aa123456789', DEFAULT_DATABASE="sha_portal", DEFAULT_LANGUAGE=US_ENGLISH
GO
ALTER LOGIN "sha_user" ENABLE
GO

USE sha_portal
GO
CREATE USER "sha_user" FOR LOGIN "sha_user" WITH DEFAULT_SCHEMA="sha_portal"
GO
ALTER ROLE [db_owner] ADD MEMBER [sha_user]
GO
