export enum EAuthority {

  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  ADD_USER = 'ADD_USER',
  EDIT_USER = 'EDIT_USER',
  CHANGE_USER_STATUS = 'CHANGE_USER_STATUS',
  RESET_PASSWORD = 'RESET_PASSWORD'
}
