export enum EAuthority {

  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  ADD_USER = 'ADD_USER',
  EDIT_USER = 'EDIT_USER',
  CHANGE_USER_STATUS = 'CHANGE_USER_STATUS',
  RESET_PASSWORD = 'RESET_PASSWORD',
  DELETE_USER = 'DELETE_USER',
  ROLE_MANAGEMENT = 'ROLE_MANAGEMENT',
  ADD_ROLE = 'ADD_ROLE',
  EDIT_ROLE = 'EDIT_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  CHANGE_ROLE_STATUS = 'CHANGE_ROLE_STATUS',
  CARD_MANAGEMENT = "CARD_MANAGEMENT",
  PRINTING_MANAGEMENT = "PRINTING_MANAGEMENT"


}
