import {Component, OnInit} from '@angular/core';
import {Card} from "@model/card.model";
import {TranslateService} from "@ngx-translate/core";
import {I18nService} from "@dcc-commons-ng/services";
import {PackageCatering} from "@model/package-catering.model";
import {ActivatedRoute, Router} from "@angular/router";
import {CardService, UserService} from "@core/services";
import {ToastService} from "@shared/components/toast";
import {Lookup} from "@model/lookup.model";
import {LookupService} from "@core/utilities/lookup.service";
import {CountryLookup} from "@model/country-lookup.model";
import {ApplicantMainData} from "@model/applicant-main-data.model";
import {Language} from "@model/enum/language.enum";
import {ApplicantRitualLite} from "@model/applicant-ritual-lite.model";
import {ApplicantHealth} from "@model/applicant-health.model";

@Component({
  selector: 'app-card-details',
  templateUrl: './card-details.component.html',
  styleUrls: ['./card-details.component.scss']
})
export class CardDetailsComponent implements OnInit {

  card: Card;
  applicant: ApplicantMainData;
  healthDetails: ApplicantHealth;
  url: any = 'assets/images/default-avatar.svg';
  //TODO: to be deleted after wiring the backend to the frontend
  hamlahPackage: any;

  ritualTypes: Lookup[] = [{"id": 1, "code": "EXTERNAL_HAJJ", "lang": "ar", "label": "حجاج الخارج"}, {
    "id": 2,
    "code": "EXTERNAL_HAJJ",
    "lang": "en",
    "label": "External Hajj"
  }, {"id": 3, "code": "INTERNAL_HAJJ", "lang": "ar", "label": "حجاج الداخل"}, {
    "id": 4,
    "code": "INTERNAL_HAJJ",
    "lang": "en",
    "label": "Internal Hajj"
  }, {"id": 5, "code": "COURTESY_HAJJ", "lang": "ar", "label": "حجاج المجاملة"}, {
    "id": 6,
    "code": "COURTESY_HAJJ",
    "lang": "en",
    "label": "Courtesy Hajj"
  }, {"id": 7, "code": "EXTERNAL_UMRAH", "lang": "ar", "label": "عمرة الخارج"}, {
    "id": 8,
    "code": "EXTERNAL_UMRAH",
    "lang": "en",
    "label": "External Umrah"
  }, {"id": 9, "code": "INTERNAL_UMRAH", "lang": "ar", "label": "عمرة الداخل"}, {
    "id": 10,
    "code": "INTERNAL_UMRAH",
    "lang": "en",
    "label": "Internal Umrah"
  }];
  relativeRelationships: Lookup[] = [{"id": 1, "code": "MOTHER", "lang": "ar", "label": "أم"}, {
    "id": 2,
    "code": "MOTHER",
    "lang": "en",
    "label": "Mother"
  }, {"id": 3, "code": "FATHER", "lang": "ar", "label": "أب"}, {
    "id": 4,
    "code": "FATHER",
    "lang": "en",
    "label": "Father"
  }, {"id": 5, "code": "WIFE", "lang": "ar", "label": "زوجة"}, {
    "id": 6,
    "code": "WIFE",
    "lang": "en",
    "label": "Wife"
  }, {"id": 7, "code": "HUSBAND", "lang": "ar", "label": "زوج"}, {
    "id": 8,
    "code": "HUSBAND",
    "lang": "en",
    "label": "Husband"
  }, {"id": 9, "code": "SON", "lang": "ar", "label": "ابن"}, {
    "id": 10,
    "code": "SON",
    "lang": "en",
    "label": "Son"
  }, {"id": 11, "code": "DAUGHTER", "lang": "ar", "label": "ابنة"}, {
    "id": 12,
    "code": "DAUGHTER",
    "lang": "en",
    "label": "Daughter"
  }, {"id": 13, "code": "BROTHER", "lang": "ar", "label": "أخ"}, {
    "id": 14,
    "code": "BROTHER",
    "lang": "en",
    "label": "Brother"
  }, {"id": 15, "code": "SISTER", "lang": "ar", "label": "أخت"}, {
    "id": 16,
    "code": "SISTER",
    "lang": "en",
    "label": "Sister"
  }, {"id": 17, "code": "RELATIVE", "lang": "ar", "label": "قريب"}, {
    "id": 18,
    "code": "RELATIVE",
    "lang": "en",
    "label": "Relative"
  }, {"id": 19, "code": "COMPANION", "lang": "ar", "label": "مرافق"}, {
    "id": 20,
    "code": "COMPANION",
    "lang": "en",
    "label": "Companion"
  }];
  countries: CountryLookup[] = [{
    "id": 1,
    "code": "AE",
    "nicCode": "101",
    "lang": "ar",
    "label": "الإمارات العربية المتحدة",
    "countryPhonePrefix": "971"
  }, {
    "id": 2,
    "code": "AE",
    "nicCode": "101",
    "lang": "en",
    "label": "Arab Emirates",
    "countryPhonePrefix": "971"
  }, {"id": 3, "code": "JO", "nicCode": "102", "lang": "ar", "label": "الاردن", "countryPhonePrefix": "962"}, {
    "id": 4,
    "code": "JO",
    "nicCode": "102",
    "lang": "en",
    "label": "Jordan",
    "countryPhonePrefix": "962"
  }, {"id": 5, "code": "BH", "nicCode": "103", "lang": "ar", "label": "البحرين", "countryPhonePrefix": "973"}, {
    "id": 6,
    "code": "BH",
    "nicCode": "103",
    "lang": "en",
    "label": "Bahrain",
    "countryPhonePrefix": "973"
  }, {"id": 7, "code": "SY", "nicCode": "104", "lang": "ar", "label": "سوريا", "countryPhonePrefix": "963"}, {
    "id": 8,
    "code": "SY",
    "nicCode": "104",
    "lang": "en",
    "label": "Syria",
    "countryPhonePrefix": "963"
  }, {"id": 9, "code": "IQ", "nicCode": "105", "lang": "ar", "label": "العراق", "countryPhonePrefix": "964"}, {
    "id": 10,
    "code": "IQ",
    "nicCode": "105",
    "lang": "en",
    "label": "Iraq",
    "countryPhonePrefix": "964"
  }, {"id": 11, "code": "OM", "nicCode": "106", "lang": "ar", "label": "عمان", "countryPhonePrefix": "968"}, {
    "id": 12,
    "code": "OM",
    "nicCode": "106",
    "lang": "en",
    "label": "Oman",
    "countryPhonePrefix": "968"
  }, {
    "id": 13,
    "code": "PS",
    "nicCode": "107",
    "lang": "ar",
    "label": "فلسطين",
    "countryPhonePrefix": "970"
  }, {
    "id": 14,
    "code": "PS",
    "nicCode": "107",
    "lang": "en",
    "label": "Palestine",
    "countryPhonePrefix": "970"
  }, {"id": 15, "code": "QA", "nicCode": "108", "lang": "ar", "label": "قطر", "countryPhonePrefix": "974"}, {
    "id": 16,
    "code": "QA",
    "nicCode": "108",
    "lang": "en",
    "label": "Qatar",
    "countryPhonePrefix": "974"
  }, {
    "id": 17,
    "code": "KW",
    "nicCode": "109",
    "lang": "ar",
    "label": "الكويت",
    "countryPhonePrefix": "965"
  }, {
    "id": 18,
    "code": "KW",
    "nicCode": "109",
    "lang": "en",
    "label": "Kuwait",
    "countryPhonePrefix": "965"
  }, {"id": 19, "code": "LB", "nicCode": "110", "lang": "ar", "label": "لبنان", "countryPhonePrefix": "961"}, {
    "id": 20,
    "code": "LB",
    "nicCode": "110",
    "lang": "en",
    "label": "Lebanon",
    "countryPhonePrefix": "961"
  }, {"id": 21, "code": "YE", "nicCode": "111", "lang": "ar", "label": "اليمن", "countryPhonePrefix": "967"}, {
    "id": 22,
    "code": "YE",
    "nicCode": "111",
    "lang": "en",
    "label": "Yemen",
    "countryPhonePrefix": "967"
  }, {
    "id": 23,
    "code": "SA",
    "nicCode": "113",
    "lang": "ar",
    "label": "العربية السعودية",
    "countryPhonePrefix": "966"
  }, {
    "id": 24,
    "code": "SA",
    "nicCode": "113",
    "lang": "en",
    "label": "Saudi Arabia",
    "countryPhonePrefix": "966"
  }, {"id": 25, "code": "TN", "nicCode": "201", "lang": "ar", "label": "تونس", "countryPhonePrefix": "216"}, {
    "id": 26,
    "code": "TN",
    "nicCode": "201",
    "lang": "en",
    "label": "Tunisia",
    "countryPhonePrefix": "216"
  }, {
    "id": 27,
    "code": "DZ",
    "nicCode": "202",
    "lang": "ar",
    "label": "الجزائر",
    "countryPhonePrefix": "213"
  }, {
    "id": 28,
    "code": "DZ",
    "nicCode": "202",
    "lang": "en",
    "label": "Algeria",
    "countryPhonePrefix": "213"
  }, {
    "id": 29,
    "code": "DJ",
    "nicCode": "203",
    "lang": "ar",
    "label": "جيبوتي",
    "countryPhonePrefix": "253"
  }, {
    "id": 30,
    "code": "DJ",
    "nicCode": "203",
    "lang": "en",
    "label": "Djibouti",
    "countryPhonePrefix": "253"
  }, {
    "id": 31,
    "code": "SD",
    "nicCode": "204",
    "lang": "ar",
    "label": "السودان",
    "countryPhonePrefix": "249"
  }, {"id": 32, "code": "SD", "nicCode": "204", "lang": "en", "label": "Sudan", "countryPhonePrefix": "249"}, {
    "id": 33,
    "code": "SO",
    "nicCode": "205",
    "lang": "ar",
    "label": "الصومال",
    "countryPhonePrefix": "252"
  }, {
    "id": 34,
    "code": "SO",
    "nicCode": "205",
    "lang": "en",
    "label": "Somalia",
    "countryPhonePrefix": "252"
  }, {"id": 35, "code": "LY", "nicCode": "206", "lang": "ar", "label": "ليبيا", "countryPhonePrefix": "218"}, {
    "id": 36,
    "code": "LY",
    "nicCode": "206",
    "lang": "en",
    "label": "Libya",
    "countryPhonePrefix": "218"
  }, {"id": 37, "code": "EG", "nicCode": "207", "lang": "ar", "label": "مصر", "countryPhonePrefix": "20"}, {
    "id": 38,
    "code": "EG",
    "nicCode": "207",
    "lang": "en",
    "label": "Egypt",
    "countryPhonePrefix": "20"
  }, {
    "id": 39,
    "code": "MA",
    "nicCode": "208",
    "lang": "ar",
    "label": "المغرب",
    "countryPhonePrefix": "212"
  }, {
    "id": 40,
    "code": "MA",
    "nicCode": "208",
    "lang": "en",
    "label": "Morocco",
    "countryPhonePrefix": "212"
  }, {
    "id": 41,
    "code": "MR",
    "nicCode": "209",
    "lang": "ar",
    "label": "موريتانيا",
    "countryPhonePrefix": "222"
  }, {
    "id": 42,
    "code": "MR",
    "nicCode": "209",
    "lang": "en",
    "label": "Mauritania",
    "countryPhonePrefix": "222"
  }, {
    "id": 43,
    "code": "AF",
    "nicCode": "301",
    "lang": "ar",
    "label": "افغانستان",
    "countryPhonePrefix": "93"
  }, {
    "id": 44,
    "code": "AF",
    "nicCode": "301",
    "lang": "en",
    "label": "Afghanistan",
    "countryPhonePrefix": "93"
  }, {
    "id": 45,
    "code": "ID",
    "nicCode": "302",
    "lang": "ar",
    "label": "اندونيسيا",
    "countryPhonePrefix": "62"
  }, {
    "id": 46,
    "code": "ID",
    "nicCode": "302",
    "lang": "en",
    "label": "Indonesia",
    "countryPhonePrefix": "62"
  }, {"id": 47, "code": "IR", "nicCode": "303", "lang": "ar", "label": "ايران", "countryPhonePrefix": "98"}, {
    "id": 48,
    "code": "IR",
    "nicCode": "303",
    "lang": "en",
    "label": "Iran",
    "countryPhonePrefix": "98"
  }, {
    "id": 49,
    "code": "PK",
    "nicCode": "304",
    "lang": "ar",
    "label": "باكستان",
    "countryPhonePrefix": "92"
  }, {
    "id": 50,
    "code": "PK",
    "nicCode": "304",
    "lang": "en",
    "label": "Pakistan",
    "countryPhonePrefix": "92"
  }, {
    "id": 51,
    "code": "BD",
    "nicCode": "305",
    "lang": "ar",
    "label": "بنجلاديش",
    "countryPhonePrefix": "880"
  }, {
    "id": 52,
    "code": "BD",
    "nicCode": "305",
    "lang": "en",
    "label": "Bangladesh",
    "countryPhonePrefix": "880"
  }, {"id": 53, "code": "BN", "nicCode": "306", "lang": "ar", "label": "بروني", "countryPhonePrefix": "673"}, {
    "id": 54,
    "code": "BN",
    "nicCode": "306",
    "lang": "en",
    "label": "Brunei",
    "countryPhonePrefix": "673"
  }, {
    "id": 55,
    "code": "MM",
    "nicCode": "307",
    "lang": "ar",
    "label": "جمهورية ميانمار",
    "countryPhonePrefix": "95"
  }, {
    "id": 56,
    "code": "MM",
    "nicCode": "307",
    "lang": "en",
    "label": "Myanmar",
    "countryPhonePrefix": "95"
  }, {"id": 57, "code": "TH", "nicCode": "308", "lang": "ar", "label": "تايلند", "countryPhonePrefix": "66"}, {
    "id": 58,
    "code": "TH",
    "nicCode": "308",
    "lang": "en",
    "label": "Thailand",
    "countryPhonePrefix": "66"
  }, {"id": 59, "code": "TR", "nicCode": "309", "lang": "ar", "label": "تركيا", "countryPhonePrefix": "90"}, {
    "id": 60,
    "code": "TR",
    "nicCode": "309",
    "lang": "en",
    "label": "Turkey",
    "countryPhonePrefix": "90"
  }, {
    "id": 61,
    "code": "MV",
    "nicCode": "310",
    "lang": "ar",
    "label": "جزر مالديف",
    "countryPhonePrefix": "960"
  }, {
    "id": 62,
    "code": "MV",
    "nicCode": "310",
    "lang": "en",
    "label": "Maldives",
    "countryPhonePrefix": "960"
  }, {
    "id": 63,
    "code": "RU",
    "nicCode": "311",
    "lang": "ar",
    "label": "روسيا الاتحادية",
    "countryPhonePrefix": "7"
  }, {"id": 64, "code": "RU", "nicCode": "311", "lang": "en", "label": "Russia", "countryPhonePrefix": "7"}, {
    "id": 65,
    "code": "SG",
    "nicCode": "312",
    "lang": "ar",
    "label": "سنغافورة",
    "countryPhonePrefix": "65"
  }, {
    "id": 66,
    "code": "SG",
    "nicCode": "312",
    "lang": "en",
    "label": "Singapore",
    "countryPhonePrefix": "65"
  }, {
    "id": 67,
    "code": "LK",
    "nicCode": "313",
    "lang": "ar",
    "label": "سري لنكا",
    "countryPhonePrefix": "94"
  }, {
    "id": 68,
    "code": "LK",
    "nicCode": "313",
    "lang": "en",
    "label": "Sri Lanka",
    "countryPhonePrefix": "94"
  }, {
    "id": 69,
    "code": "PH",
    "nicCode": "315",
    "lang": "ar",
    "label": "الفلبين",
    "countryPhonePrefix": "63"
  }, {
    "id": 70,
    "code": "PH",
    "nicCode": "315",
    "lang": "en",
    "label": "Philippines",
    "countryPhonePrefix": "63"
  }, {"id": 71, "code": "VN", "nicCode": "316", "lang": "ar", "label": "فيتنام", "countryPhonePrefix": "84"}, {
    "id": 72,
    "code": "VN",
    "nicCode": "316",
    "lang": "en",
    "label": "Vietnam",
    "countryPhonePrefix": "84"
  }, {
    "id": 73,
    "code": "KH",
    "nicCode": "317",
    "lang": "ar",
    "label": "كمبوديا",
    "countryPhonePrefix": "855"
  }, {
    "id": 74,
    "code": "KH",
    "nicCode": "317",
    "lang": "en",
    "label": "Cambodia",
    "countryPhonePrefix": "855"
  }, {
    "id": 75,
    "code": "KR",
    "nicCode": "318",
    "lang": "ar",
    "label": "كوريا الجنوبية",
    "countryPhonePrefix": "82"
  }, {
    "id": 76,
    "code": "KR",
    "nicCode": "318",
    "lang": "en",
    "label": "South Korea",
    "countryPhonePrefix": "82"
  }, {
    "id": 77,
    "code": "MY",
    "nicCode": "319",
    "lang": "ar",
    "label": "ماليزيا",
    "countryPhonePrefix": "60"
  }, {
    "id": 78,
    "code": "MY",
    "nicCode": "319",
    "lang": "en",
    "label": "Malaysia",
    "countryPhonePrefix": "60"
  }, {"id": 79, "code": "NP", "nicCode": "320", "lang": "ar", "label": "نيبال", "countryPhonePrefix": "977"}, {
    "id": 80,
    "code": "NP",
    "nicCode": "320",
    "lang": "en",
    "label": "Nepal",
    "countryPhonePrefix": "977"
  }, {"id": 81, "code": "IN", "nicCode": "321", "lang": "ar", "label": "الهند", "countryPhonePrefix": "91"}, {
    "id": 82,
    "code": "IN",
    "nicCode": "321",
    "lang": "en",
    "label": "India",
    "countryPhonePrefix": "91"
  }, {
    "id": 83,
    "code": "HK",
    "nicCode": "322",
    "lang": "ar",
    "label": "هونج كونج",
    "countryPhonePrefix": "852"
  }, {
    "id": 84,
    "code": "HK",
    "nicCode": "322",
    "lang": "en",
    "label": "Hong Kong",
    "countryPhonePrefix": "852"
  }, {
    "id": 85,
    "code": "JP",
    "nicCode": "323",
    "lang": "ar",
    "label": "اليابان",
    "countryPhonePrefix": "81"
  }, {"id": 86, "code": "JP", "nicCode": "323", "lang": "en", "label": "Japan", "countryPhonePrefix": "81"}, {
    "id": 87,
    "code": "BT",
    "nicCode": "324",
    "lang": "ar",
    "label": "بهوتان",
    "countryPhonePrefix": "975"
  }, {
    "id": 88,
    "code": "BT",
    "nicCode": "324",
    "lang": "en",
    "label": "Bhutan",
    "countryPhonePrefix": "975"
  }, {
    "id": 89,
    "code": "CN",
    "nicCode": "325",
    "lang": "ar",
    "label": "الصين الشعبية",
    "countryPhonePrefix": "86"
  }, {"id": 90, "code": "CN", "nicCode": "325", "lang": "en", "label": "China", "countryPhonePrefix": "86"}, {
    "id": 91,
    "code": "CY",
    "nicCode": "326",
    "lang": "ar",
    "label": "قبرص",
    "countryPhonePrefix": "357"
  }, {
    "id": 92,
    "code": "CY",
    "nicCode": "326",
    "lang": "en",
    "label": "Cyprus",
    "countryPhonePrefix": "357"
  }, {
    "id": 93,
    "code": "KP",
    "nicCode": "328",
    "lang": "ar",
    "label": "كوريا الشمالية",
    "countryPhonePrefix": "850"
  }, {
    "id": 94,
    "code": "KP",
    "nicCode": "328",
    "lang": "en",
    "label": "North Korea",
    "countryPhonePrefix": "850"
  }, {"id": 95, "code": "LA", "nicCode": "329", "lang": "ar", "label": "لاوس", "countryPhonePrefix": "856"}, {
    "id": 96,
    "code": "LA",
    "nicCode": "329",
    "lang": "en",
    "label": "Laos",
    "countryPhonePrefix": "856"
  }, {
    "id": 97,
    "code": "MN",
    "nicCode": "330",
    "lang": "ar",
    "label": "منغوليا",
    "countryPhonePrefix": "976"
  }, {
    "id": 98,
    "code": "MN",
    "nicCode": "330",
    "lang": "en",
    "label": "Mongolia",
    "countryPhonePrefix": "976"
  }, {
    "id": 99,
    "code": "MO",
    "nicCode": "331",
    "lang": "ar",
    "label": "ماكاو",
    "countryPhonePrefix": "853"
  }, {
    "id": 100,
    "code": "MO",
    "nicCode": "331",
    "lang": "en",
    "label": "Macao",
    "countryPhonePrefix": "853"
  }, {
    "id": 101,
    "code": "KZ-YUZ",
    "nicCode": "332",
    "lang": "ar",
    "label": "تركستان",
    "countryPhonePrefix": "7-72533"
  }, {
    "id": 102,
    "code": "KZ-YUZ",
    "nicCode": "332",
    "lang": "en",
    "label": "Turkistan",
    "countryPhonePrefix": "7-72533"
  }, {
    "id": 103,
    "code": "KZ",
    "nicCode": "336",
    "lang": "ar",
    "label": "كازاخستان",
    "countryPhonePrefix": "7"
  }, {
    "id": 104,
    "code": "KZ",
    "nicCode": "336",
    "lang": "en",
    "label": "Kazakhstan",
    "countryPhonePrefix": "7"
  }, {
    "id": 105,
    "code": "UZ",
    "nicCode": "337",
    "lang": "ar",
    "label": "ازبكستان",
    "countryPhonePrefix": "998"
  }, {
    "id": 106,
    "code": "UZ",
    "nicCode": "337",
    "lang": "en",
    "label": "Uzbekistan",
    "countryPhonePrefix": "998"
  }, {
    "id": 107,
    "code": "TM",
    "nicCode": "338",
    "lang": "ar",
    "label": "تركمانستان",
    "countryPhonePrefix": "993"
  }, {
    "id": 108,
    "code": "TM",
    "nicCode": "338",
    "lang": "en",
    "label": "Turkmenistan",
    "countryPhonePrefix": "993"
  }, {
    "id": 109,
    "code": "TJ",
    "nicCode": "339",
    "lang": "ar",
    "label": "طاجكستان",
    "countryPhonePrefix": "992"
  }, {
    "id": 110,
    "code": "TJ",
    "nicCode": "339",
    "lang": "en",
    "label": "Tajikistan",
    "countryPhonePrefix": "992"
  }, {
    "id": 111,
    "code": "KG",
    "nicCode": "340",
    "lang": "ar",
    "label": "قرغيزستان",
    "countryPhonePrefix": "996"
  }, {
    "id": 112,
    "code": "KG",
    "nicCode": "340",
    "lang": "en",
    "label": "kyrgyzstan",
    "countryPhonePrefix": "996"
  }, {
    "id": 113,
    "code": "AZ",
    "nicCode": "343",
    "lang": "ar",
    "label": "اذربيجان",
    "countryPhonePrefix": "994"
  }, {
    "id": 114,
    "code": "AZ",
    "nicCode": "343",
    "lang": "en",
    "label": "Azerbaijan",
    "countryPhonePrefix": "994"
  }, {
    "id": 115,
    "code": "RU-CE",
    "nicCode": "344",
    "lang": "ar",
    "label": "الشاشان",
    "countryPhonePrefix": "7-871"
  }, {
    "id": 116,
    "code": "RU-CE",
    "nicCode": "344",
    "lang": "en",
    "label": "Chechnya",
    "countryPhonePrefix": "7-871"
  }, {
    "id": 117,
    "code": "RU-DA",
    "nicCode": "345",
    "lang": "ar",
    "label": "داغستان",
    "countryPhonePrefix": "7-872"
  }, {
    "id": 118,
    "code": "RU-DA",
    "nicCode": "345",
    "lang": "en",
    "label": "Dagestan",
    "countryPhonePrefix": "7-872"
  }, {
    "id": 119,
    "code": "RU-TA",
    "nicCode": "347",
    "lang": "ar",
    "label": "تتارستان",
    "countryPhonePrefix": "7-843"
  }, {
    "id": 120,
    "code": "RU-TA",
    "nicCode": "347",
    "lang": "en",
    "label": "Tatarstan",
    "countryPhonePrefix": "7-843"
  }, {
    "id": 121,
    "code": "TL",
    "nicCode": "349",
    "lang": "ar",
    "label": "تيمور الشرقية",
    "countryPhonePrefix": "670"
  }, {
    "id": 122,
    "code": "TL",
    "nicCode": "349",
    "lang": "en",
    "label": "East Timor",
    "countryPhonePrefix": "670"
  }, {
    "id": 123,
    "code": "ET",
    "nicCode": "401",
    "lang": "ar",
    "label": "اثيوبيا",
    "countryPhonePrefix": "251"
  }, {
    "id": 124,
    "code": "ET",
    "nicCode": "401",
    "lang": "en",
    "label": "Ethiopia",
    "countryPhonePrefix": "251"
  }, {
    "id": 125,
    "code": "UG",
    "nicCode": "402",
    "lang": "ar",
    "label": "اوغندة",
    "countryPhonePrefix": "256"
  }, {
    "id": 126,
    "code": "UG",
    "nicCode": "402",
    "lang": "en",
    "label": "Uganda",
    "countryPhonePrefix": "256"
  }, {
    "id": 127,
    "code": "BW",
    "nicCode": "403",
    "lang": "ar",
    "label": "بوتسوانا",
    "countryPhonePrefix": "267"
  }, {
    "id": 128,
    "code": "BW",
    "nicCode": "403",
    "lang": "en",
    "label": "Botswana",
    "countryPhonePrefix": "267"
  }, {
    "id": 129,
    "code": "BI",
    "nicCode": "404",
    "lang": "ar",
    "label": "بورندي",
    "countryPhonePrefix": "257"
  }, {
    "id": 130,
    "code": "BI",
    "nicCode": "404",
    "lang": "en",
    "label": "Burundi",
    "countryPhonePrefix": "257"
  }, {
    "id": 131,
    "code": "TD",
    "nicCode": "405",
    "lang": "ar",
    "label": "تشاد",
    "countryPhonePrefix": "235"
  }, {
    "id": 132,
    "code": "TD",
    "nicCode": "405",
    "lang": "en",
    "label": "Chad",
    "countryPhonePrefix": "235"
  }, {
    "id": 133,
    "code": "TZ",
    "nicCode": "406",
    "lang": "ar",
    "label": "تنزانيا",
    "countryPhonePrefix": "255"
  }, {
    "id": 134,
    "code": "TZ",
    "nicCode": "406",
    "lang": "en",
    "label": "Tanzania",
    "countryPhonePrefix": "255"
  }, {
    "id": 135,
    "code": "TG",
    "nicCode": "407",
    "lang": "ar",
    "label": "توجو",
    "countryPhonePrefix": "228"
  }, {
    "id": 136,
    "code": "TG",
    "nicCode": "407",
    "lang": "en",
    "label": "Togo",
    "countryPhonePrefix": "228"
  }, {
    "id": 137,
    "code": "GA",
    "nicCode": "408",
    "lang": "ar",
    "label": "الغابون",
    "countryPhonePrefix": "241"
  }, {
    "id": 138,
    "code": "GA",
    "nicCode": "408",
    "lang": "en",
    "label": "Gabon",
    "countryPhonePrefix": "241"
  }, {
    "id": 139,
    "code": "GM",
    "nicCode": "409",
    "lang": "ar",
    "label": "غامبيا",
    "countryPhonePrefix": "220"
  }, {
    "id": 140,
    "code": "GM",
    "nicCode": "409",
    "lang": "en",
    "label": "Gambia",
    "countryPhonePrefix": "220"
  }, {
    "id": 141,
    "code": "KM",
    "nicCode": "410",
    "lang": "ar",
    "label": "جزر القمر",
    "countryPhonePrefix": "269"
  }, {
    "id": 142,
    "code": "KM",
    "nicCode": "410",
    "lang": "en",
    "label": "Comoros",
    "countryPhonePrefix": "269"
  }, {
    "id": 143,
    "code": "ZA",
    "nicCode": "411",
    "lang": "ar",
    "label": "جنوب افريقيا",
    "countryPhonePrefix": "27"
  }, {
    "id": 144,
    "code": "ZA",
    "nicCode": "411",
    "lang": "en",
    "label": "South Africa",
    "countryPhonePrefix": "27"
  }, {
    "id": 145,
    "code": "NA",
    "nicCode": "412",
    "lang": "ar",
    "label": "ناميبيا",
    "countryPhonePrefix": "264"
  }, {
    "id": 146,
    "code": "NA",
    "nicCode": "412",
    "lang": "en",
    "label": "Namibia",
    "countryPhonePrefix": "264"
  }, {
    "id": 147,
    "code": "BJ",
    "nicCode": "413",
    "lang": "ar",
    "label": "بنين",
    "countryPhonePrefix": "229"
  }, {
    "id": 148,
    "code": "BJ",
    "nicCode": "413",
    "lang": "en",
    "label": "Benin",
    "countryPhonePrefix": "229"
  }, {
    "id": 149,
    "code": "RW",
    "nicCode": "414",
    "lang": "ar",
    "label": "رواندا",
    "countryPhonePrefix": "250"
  }, {
    "id": 150,
    "code": "RW",
    "nicCode": "414",
    "lang": "en",
    "label": "Rwanda",
    "countryPhonePrefix": "250"
  }, {
    "id": 151,
    "code": "ZW",
    "nicCode": "415",
    "lang": "ar",
    "label": "زمبابوي",
    "countryPhonePrefix": "263"
  }, {
    "id": 152,
    "code": "ZW",
    "nicCode": "415",
    "lang": "en",
    "label": "Zimbabwe",
    "countryPhonePrefix": "263"
  }, {
    "id": 153,
    "code": "CD",
    "nicCode": "416",
    "lang": "ar",
    "label": "الكونغو الديمقراطية",
    "countryPhonePrefix": "243"
  }, {
    "id": 154,
    "code": "CD",
    "nicCode": "416",
    "lang": "en",
    "label": "Zaire",
    "countryPhonePrefix": "243"
  }, {
    "id": 155,
    "code": "ZM",
    "nicCode": "417",
    "lang": "ar",
    "label": "زامبيا",
    "countryPhonePrefix": "260"
  }, {
    "id": 156,
    "code": "ZM",
    "nicCode": "417",
    "lang": "en",
    "label": "Zambia",
    "countryPhonePrefix": "260"
  }, {
    "id": 157,
    "code": "CI",
    "nicCode": "418",
    "lang": "ar",
    "label": "ساحل العاج",
    "countryPhonePrefix": "225"
  }, {
    "id": 158,
    "code": "CI",
    "nicCode": "418",
    "lang": "en",
    "label": "Ivory Coast",
    "countryPhonePrefix": "225"
  }, {
    "id": 159,
    "code": "SN",
    "nicCode": "419",
    "lang": "ar",
    "label": "السنغال",
    "countryPhonePrefix": "221"
  }, {
    "id": 160,
    "code": "SN",
    "nicCode": "419",
    "lang": "en",
    "label": "Senegal",
    "countryPhonePrefix": "221"
  }, {
    "id": 161,
    "code": "SL",
    "nicCode": "420",
    "lang": "ar",
    "label": "سيراليون",
    "countryPhonePrefix": "232"
  }, {
    "id": 162,
    "code": "SL",
    "nicCode": "420",
    "lang": "en",
    "label": "Sierra Leone",
    "countryPhonePrefix": "232"
  }, {
    "id": 163,
    "code": "GH",
    "nicCode": "421",
    "lang": "ar",
    "label": "غانا",
    "countryPhonePrefix": "233"
  }, {
    "id": 164,
    "code": "GH",
    "nicCode": "421",
    "lang": "en",
    "label": "Ghana",
    "countryPhonePrefix": "233"
  }, {
    "id": 165,
    "code": "GN",
    "nicCode": "422",
    "lang": "ar",
    "label": "غينيا",
    "countryPhonePrefix": "224"
  }, {
    "id": 166,
    "code": "GN",
    "nicCode": "422",
    "lang": "en",
    "label": "Guinea",
    "countryPhonePrefix": "224"
  }, {
    "id": 167,
    "code": "GW",
    "nicCode": "423",
    "lang": "ar",
    "label": "غينيابيساو",
    "countryPhonePrefix": "245"
  }, {
    "id": 168,
    "code": "GW",
    "nicCode": "423",
    "lang": "en",
    "label": "Guinea Bissau",
    "countryPhonePrefix": "245"
  }, {
    "id": 169,
    "code": "BF",
    "nicCode": "424",
    "lang": "ar",
    "label": "بوركينافاسو",
    "countryPhonePrefix": "226"
  }, {
    "id": 170,
    "code": "BF",
    "nicCode": "424",
    "lang": "en",
    "label": "Burkina Faso",
    "countryPhonePrefix": "226"
  }, {
    "id": 171,
    "code": "CM",
    "nicCode": "425",
    "lang": "ar",
    "label": "الكاميرون",
    "countryPhonePrefix": "237"
  }, {
    "id": 172,
    "code": "CM",
    "nicCode": "425",
    "lang": "en",
    "label": "Cameroon",
    "countryPhonePrefix": "237"
  }, {
    "id": 173,
    "code": "CG",
    "nicCode": "426",
    "lang": "ar",
    "label": "الكونغو",
    "countryPhonePrefix": "242"
  }, {
    "id": 174,
    "code": "CG",
    "nicCode": "426",
    "lang": "en",
    "label": "Congo",
    "countryPhonePrefix": "242"
  }, {
    "id": 175,
    "code": "KE",
    "nicCode": "427",
    "lang": "ar",
    "label": "كينيا",
    "countryPhonePrefix": "254"
  }, {
    "id": 176,
    "code": "KE",
    "nicCode": "427",
    "lang": "en",
    "label": "Kenya",
    "countryPhonePrefix": "254"
  }, {
    "id": 177,
    "code": "LS",
    "nicCode": "428",
    "lang": "ar",
    "label": "ليسوتو",
    "countryPhonePrefix": "266"
  }, {
    "id": 178,
    "code": "LS",
    "nicCode": "428",
    "lang": "en",
    "label": "Lesotho",
    "countryPhonePrefix": "266"
  }, {
    "id": 179,
    "code": "LR",
    "nicCode": "429",
    "lang": "ar",
    "label": "ليبيريا",
    "countryPhonePrefix": "231"
  }, {
    "id": 180,
    "code": "LR",
    "nicCode": "429",
    "lang": "en",
    "label": "Liberia",
    "countryPhonePrefix": "231"
  }, {
    "id": 181,
    "code": "ML",
    "nicCode": "430",
    "lang": "ar",
    "label": "مالي",
    "countryPhonePrefix": "223"
  }, {
    "id": 182,
    "code": "ML",
    "nicCode": "430",
    "lang": "en",
    "label": "Mali",
    "countryPhonePrefix": "223"
  }, {
    "id": 183,
    "code": "MW",
    "nicCode": "432",
    "lang": "ar",
    "label": "ملاوي",
    "countryPhonePrefix": "265"
  }, {
    "id": 184,
    "code": "MW",
    "nicCode": "432",
    "lang": "en",
    "label": "Malawi",
    "countryPhonePrefix": "265"
  }, {
    "id": 185,
    "code": "MU",
    "nicCode": "433",
    "lang": "ar",
    "label": "موريشيوس",
    "countryPhonePrefix": "230"
  }, {
    "id": 186,
    "code": "MU",
    "nicCode": "433",
    "lang": "en",
    "label": "Mauritius",
    "countryPhonePrefix": "230"
  }, {
    "id": 187,
    "code": "MZ",
    "nicCode": "434",
    "lang": "ar",
    "label": "موزمبيق",
    "countryPhonePrefix": "258"
  }, {
    "id": 188,
    "code": "MZ",
    "nicCode": "434",
    "lang": "en",
    "label": "Mozambique",
    "countryPhonePrefix": "258"
  }, {
    "id": 189,
    "code": "NG",
    "nicCode": "435",
    "lang": "ar",
    "label": "نيجيريا",
    "countryPhonePrefix": "234"
  }, {
    "id": 190,
    "code": "NG",
    "nicCode": "435",
    "lang": "en",
    "label": "Nigeria",
    "countryPhonePrefix": "234"
  }, {
    "id": 191,
    "code": "NE",
    "nicCode": "436",
    "lang": "ar",
    "label": "النيجر",
    "countryPhonePrefix": "227"
  }, {
    "id": 192,
    "code": "NE",
    "nicCode": "436",
    "lang": "en",
    "label": "Niger",
    "countryPhonePrefix": "227"
  }, {
    "id": 193,
    "code": "CF",
    "nicCode": "437",
    "lang": "ar",
    "label": "افريقيا الوسطى",
    "countryPhonePrefix": "236"
  }, {
    "id": 194,
    "code": "CF",
    "nicCode": "437",
    "lang": "en",
    "label": "Central Africa",
    "countryPhonePrefix": "236"
  }, {
    "id": 195,
    "code": "AO",
    "nicCode": "438",
    "lang": "ar",
    "label": "انجولا",
    "countryPhonePrefix": "244"
  }, {
    "id": 196,
    "code": "AO",
    "nicCode": "438",
    "lang": "en",
    "label": "Angola",
    "countryPhonePrefix": "244"
  }, {
    "id": 197,
    "code": "CV",
    "nicCode": "439",
    "lang": "ar",
    "label": "الراس الاخضر",
    "countryPhonePrefix": "238"
  }, {
    "id": 198,
    "code": "CV",
    "nicCode": "439",
    "lang": "en",
    "label": "Cape Verde",
    "countryPhonePrefix": "238"
  }, {
    "id": 199,
    "code": "GQ",
    "nicCode": "440",
    "lang": "ar",
    "label": "غينيا الاستوائية",
    "countryPhonePrefix": "240"
  }, {
    "id": 200,
    "code": "GQ",
    "nicCode": "440",
    "lang": "en",
    "label": "Equatorial Guinea",
    "countryPhonePrefix": "240"
  }, {
    "id": 201,
    "code": "MG",
    "nicCode": "441",
    "lang": "ar",
    "label": "مدغشقر",
    "countryPhonePrefix": "261"
  }, {
    "id": 202,
    "code": "MG",
    "nicCode": "441",
    "lang": "en",
    "label": "Mlajasi",
    "countryPhonePrefix": "261"
  }, {
    "id": 203,
    "code": "ST",
    "nicCode": "442",
    "lang": "ar",
    "label": "ساوتومي/برنسبى",
    "countryPhonePrefix": "239"
  }, {
    "id": 204,
    "code": "ST",
    "nicCode": "442",
    "lang": "en",
    "label": "São Tomé and Príncipe",
    "countryPhonePrefix": "239"
  }, {
    "id": 205,
    "code": "SC",
    "nicCode": "443",
    "lang": "ar",
    "label": "جزر سيشل",
    "countryPhonePrefix": "248"
  }, {
    "id": 206,
    "code": "SC",
    "nicCode": "443",
    "lang": "en",
    "label": "Seychelles Islands",
    "countryPhonePrefix": "248"
  }, {
    "id": 207,
    "code": "SZ",
    "nicCode": "444",
    "lang": "ar",
    "label": "اسواتيني",
    "countryPhonePrefix": "268"
  }, {
    "id": 208,
    "code": "SZ",
    "nicCode": "444",
    "lang": "en",
    "label": "Swaziland",
    "countryPhonePrefix": "268"
  }, {
    "id": 209,
    "code": "ER",
    "nicCode": "449",
    "lang": "ar",
    "label": "ارتيريا",
    "countryPhonePrefix": "291"
  }, {
    "id": 210,
    "code": "ER",
    "nicCode": "449",
    "lang": "en",
    "label": "Eritrea",
    "countryPhonePrefix": "291"
  }, {
    "id": 211,
    "code": "SS",
    "nicCode": "453",
    "lang": "ar",
    "label": "جمهورية جنوب السودان",
    "countryPhonePrefix": "211"
  }, {
    "id": 212,
    "code": "SS",
    "nicCode": "453",
    "lang": "en",
    "label": "Republic of South Sudan",
    "countryPhonePrefix": "211"
  }, {
    "id": 213,
    "code": "ES",
    "nicCode": "501",
    "lang": "ar",
    "label": "اسبانيا",
    "countryPhonePrefix": "34"
  }, {
    "id": 214,
    "code": "ES",
    "nicCode": "501",
    "lang": "en",
    "label": "Spain",
    "countryPhonePrefix": "34"
  }, {
    "id": 215,
    "code": "AL",
    "nicCode": "502",
    "lang": "ar",
    "label": "البانيا",
    "countryPhonePrefix": "355"
  }, {
    "id": 216,
    "code": "AL",
    "nicCode": "502",
    "lang": "en",
    "label": "Albania",
    "countryPhonePrefix": "355"
  }, {
    "id": 217,
    "code": "DE",
    "nicCode": "503",
    "lang": "ar",
    "label": "المانيا",
    "countryPhonePrefix": "49"
  }, {
    "id": 218,
    "code": "DE",
    "nicCode": "503",
    "lang": "en",
    "label": "Germany",
    "countryPhonePrefix": "49"
  }, {
    "id": 219,
    "code": "IE",
    "nicCode": "504",
    "lang": "ar",
    "label": "ايرلندا",
    "countryPhonePrefix": "353"
  }, {
    "id": 220,
    "code": "IE",
    "nicCode": "504",
    "lang": "en",
    "label": "Ireland",
    "countryPhonePrefix": "353"
  }, {
    "id": 221,
    "code": "IT",
    "nicCode": "505",
    "lang": "ar",
    "label": "ايطاليا",
    "countryPhonePrefix": "39"
  }, {
    "id": 222,
    "code": "IT",
    "nicCode": "505",
    "lang": "en",
    "label": "Italy",
    "countryPhonePrefix": "39"
  }, {
    "id": 223,
    "code": "GB",
    "nicCode": "506",
    "lang": "ar",
    "label": "المملكة المتحدة",
    "countryPhonePrefix": "44"
  }, {
    "id": 224,
    "code": "GB",
    "nicCode": "506",
    "lang": "en",
    "label": "United Kingdom",
    "countryPhonePrefix": "44"
  }, {
    "id": 225,
    "code": "PT",
    "nicCode": "507",
    "lang": "ar",
    "label": "البرتغال",
    "countryPhonePrefix": "351"
  }, {
    "id": 226,
    "code": "PT",
    "nicCode": "507",
    "lang": "en",
    "label": "Portugal",
    "countryPhonePrefix": "351"
  }, {
    "id": 227,
    "code": "BG",
    "nicCode": "508",
    "lang": "ar",
    "label": "بلغاريا",
    "countryPhonePrefix": "359"
  }, {
    "id": 228,
    "code": "BG",
    "nicCode": "508",
    "lang": "en",
    "label": "Bulgaria",
    "countryPhonePrefix": "359"
  }, {
    "id": 229,
    "code": "BE",
    "nicCode": "509",
    "lang": "ar",
    "label": "بلجيكا",
    "countryPhonePrefix": "32"
  }, {
    "id": 230,
    "code": "BE",
    "nicCode": "509",
    "lang": "en",
    "label": "Belgium",
    "countryPhonePrefix": "32"
  }, {
    "id": 231,
    "code": "PL",
    "nicCode": "510",
    "lang": "ar",
    "label": "بولندا",
    "countryPhonePrefix": "48"
  }, {
    "id": 232,
    "code": "PL",
    "nicCode": "510",
    "lang": "en",
    "label": "Poland",
    "countryPhonePrefix": "48"
  }, {
    "id": 233,
    "code": "DK",
    "nicCode": "512",
    "lang": "ar",
    "label": "الدانمارك",
    "countryPhonePrefix": "45"
  }, {
    "id": 234,
    "code": "DK",
    "nicCode": "512",
    "lang": "en",
    "label": "Denmark",
    "countryPhonePrefix": "45"
  }, {
    "id": 235,
    "code": "RO",
    "nicCode": "513",
    "lang": "ar",
    "label": "رومانيا",
    "countryPhonePrefix": "40"
  }, {
    "id": 236,
    "code": "RO",
    "nicCode": "513",
    "lang": "en",
    "label": "Romania",
    "countryPhonePrefix": "40"
  }, {
    "id": 237,
    "code": "SE",
    "nicCode": "514",
    "lang": "ar",
    "label": "السويد",
    "countryPhonePrefix": "46"
  }, {
    "id": 238,
    "code": "SE",
    "nicCode": "514",
    "lang": "en",
    "label": "Sweden",
    "countryPhonePrefix": "46"
  }, {
    "id": 239,
    "code": "CH",
    "nicCode": "515",
    "lang": "ar",
    "label": "سويسرا",
    "countryPhonePrefix": "41"
  }, {
    "id": 240,
    "code": "CH",
    "nicCode": "515",
    "lang": "en",
    "label": "Switzerland",
    "countryPhonePrefix": "41"
  }, {
    "id": 241,
    "code": "FR",
    "nicCode": "516",
    "lang": "ar",
    "label": "فرنسا",
    "countryPhonePrefix": "33"
  }, {
    "id": 242,
    "code": "FR",
    "nicCode": "516",
    "lang": "en",
    "label": "France",
    "countryPhonePrefix": "33"
  }, {
    "id": 243,
    "code": "AX",
    "nicCode": "517",
    "lang": "ar",
    "label": "فنلندا",
    "countryPhonePrefix": "358"
  }, {
    "id": 244,
    "code": "AX",
    "nicCode": "517",
    "lang": "en",
    "label": "Finland",
    "countryPhonePrefix": "358"
  }, {
    "id": 245,
    "code": "RS",
    "nicCode": "518",
    "lang": "ar",
    "label": "صربيا",
    "countryPhonePrefix": "381"
  }, {
    "id": 246,
    "code": "RS",
    "nicCode": "518",
    "lang": "en",
    "label": "Serbia",
    "countryPhonePrefix": "381"
  }, {
    "id": 247,
    "code": "NL",
    "nicCode": "519",
    "lang": "ar",
    "label": "هولندا",
    "countryPhonePrefix": "31"
  }, {
    "id": 248,
    "code": "NL",
    "nicCode": "519",
    "lang": "en",
    "label": "Netherlands",
    "countryPhonePrefix": "31"
  }, {
    "id": 249,
    "code": "GR",
    "nicCode": "521",
    "lang": "ar",
    "label": "اليونان",
    "countryPhonePrefix": "30"
  }, {
    "id": 250,
    "code": "GR",
    "nicCode": "521",
    "lang": "en",
    "label": "Greece",
    "countryPhonePrefix": "30"
  }, {
    "id": 251,
    "code": "AD",
    "nicCode": "522",
    "lang": "ar",
    "label": "اندورا",
    "countryPhonePrefix": "376"
  }, {
    "id": 252,
    "code": "AD",
    "nicCode": "522",
    "lang": "en",
    "label": "Andorra",
    "countryPhonePrefix": "376"
  }, {
    "id": 253,
    "code": "AT",
    "nicCode": "523",
    "lang": "ar",
    "label": "النمسا",
    "countryPhonePrefix": "43"
  }, {
    "id": 254,
    "code": "AT",
    "nicCode": "523",
    "lang": "en",
    "label": "Austria",
    "countryPhonePrefix": "43"
  }, {
    "id": 255,
    "code": "ME",
    "nicCode": "524",
    "lang": "ar",
    "label": "الجبل الأ سود",
    "countryPhonePrefix": "382"
  }, {
    "id": 256,
    "code": "ME",
    "nicCode": "524",
    "lang": "en",
    "label": "Montenegro",
    "countryPhonePrefix": "382"
  }, {
    "id": 257,
    "code": "HU",
    "nicCode": "525",
    "lang": "ar",
    "label": "هنغاريا",
    "countryPhonePrefix": "36"
  }, {
    "id": 258,
    "code": "HU",
    "nicCode": "525",
    "lang": "en",
    "label": "Hungary",
    "countryPhonePrefix": "36"
  }, {
    "id": 259,
    "code": "IS",
    "nicCode": "526",
    "lang": "ar",
    "label": "ايسلندا",
    "countryPhonePrefix": "354"
  }, {
    "id": 260,
    "code": "IS",
    "nicCode": "526",
    "lang": "en",
    "label": "Iceland",
    "countryPhonePrefix": "354"
  }, {
    "id": 261,
    "code": "LI",
    "nicCode": "527",
    "lang": "ar",
    "label": "ليختنشتين",
    "countryPhonePrefix": "423"
  }, {
    "id": 262,
    "code": "LI",
    "nicCode": "527",
    "lang": "en",
    "label": "Liechtenstein",
    "countryPhonePrefix": "423"
  }, {
    "id": 263,
    "code": "LU",
    "nicCode": "528",
    "lang": "ar",
    "label": "لوكسمبورغ",
    "countryPhonePrefix": "352"
  }, {
    "id": 264,
    "code": "LU",
    "nicCode": "528",
    "lang": "en",
    "label": "Luxembourg",
    "countryPhonePrefix": "352"
  }, {
    "id": 265,
    "code": "MT",
    "nicCode": "529",
    "lang": "ar",
    "label": "مالطا",
    "countryPhonePrefix": "356"
  }, {
    "id": 266,
    "code": "MT",
    "nicCode": "529",
    "lang": "en",
    "label": "Malta",
    "countryPhonePrefix": "356"
  }, {
    "id": 267,
    "code": "MC",
    "nicCode": "530",
    "lang": "ar",
    "label": "موناكو",
    "countryPhonePrefix": "377"
  }, {
    "id": 268,
    "code": "MC",
    "nicCode": "530",
    "lang": "en",
    "label": "Monaco",
    "countryPhonePrefix": "377"
  }, {
    "id": 269,
    "code": "SJ",
    "nicCode": "531",
    "lang": "ar",
    "label": "النرويج",
    "countryPhonePrefix": "47"
  }, {
    "id": 270,
    "code": "SJ",
    "nicCode": "531",
    "lang": "en",
    "label": "Norway",
    "countryPhonePrefix": "47"
  }, {
    "id": 271,
    "code": "SM",
    "nicCode": "532",
    "lang": "ar",
    "label": "سان مارينو",
    "countryPhonePrefix": "378"
  }, {
    "id": 272,
    "code": "SM",
    "nicCode": "532",
    "lang": "en",
    "label": "San Marino",
    "countryPhonePrefix": "378"
  }, {
    "id": 273,
    "code": "VA",
    "nicCode": "533",
    "lang": "ar",
    "label": "مدينة الفاتيكان",
    "countryPhonePrefix": "39-06"
  }, {
    "id": 274,
    "code": "VA",
    "nicCode": "533",
    "lang": "en",
    "label": "Vatican City",
    "countryPhonePrefix": "39-06"
  }, {
    "id": 275,
    "code": "GI",
    "nicCode": "534",
    "lang": "ar",
    "label": "جبل طارق",
    "countryPhonePrefix": "350"
  }, {
    "id": 276,
    "code": "GI",
    "nicCode": "534",
    "lang": "en",
    "label": "Gibraltar",
    "countryPhonePrefix": "350"
  }, {
    "id": 277,
    "code": "UA",
    "nicCode": "536",
    "lang": "ar",
    "label": "اوكرانيا",
    "countryPhonePrefix": "380"
  }, {
    "id": 278,
    "code": "UA",
    "nicCode": "536",
    "lang": "en",
    "label": "Ukraine",
    "countryPhonePrefix": "380"
  }, {
    "id": 279,
    "code": "BY",
    "nicCode": "537",
    "lang": "ar",
    "label": "روسيا البيضاء",
    "countryPhonePrefix": "375"
  }, {
    "id": 280,
    "code": "BY",
    "nicCode": "537",
    "lang": "en",
    "label": "Byelorussia",
    "countryPhonePrefix": "375"
  }, {
    "id": 281,
    "code": "AM",
    "nicCode": "539",
    "lang": "ar",
    "label": "ارمينيا",
    "countryPhonePrefix": "374"
  }, {
    "id": 282,
    "code": "AM",
    "nicCode": "539",
    "lang": "en",
    "label": "Armenia",
    "countryPhonePrefix": "374"
  }, {
    "id": 283,
    "code": "MD",
    "nicCode": "540",
    "lang": "ar",
    "label": "مولدافيا",
    "countryPhonePrefix": "373"
  }, {
    "id": 284,
    "code": "MD",
    "nicCode": "540",
    "lang": "en",
    "label": "Moldova",
    "countryPhonePrefix": "373"
  }, {
    "id": 285,
    "code": "GE",
    "nicCode": "541",
    "lang": "ar",
    "label": "جورجيا",
    "countryPhonePrefix": "995"
  }, {
    "id": 286,
    "code": "GE",
    "nicCode": "541",
    "lang": "en",
    "label": "Georgia",
    "countryPhonePrefix": "995"
  }, {
    "id": 287,
    "code": "LT",
    "nicCode": "542",
    "lang": "ar",
    "label": "ليتوانيا",
    "countryPhonePrefix": "370"
  }, {
    "id": 288,
    "code": "LT",
    "nicCode": "542",
    "lang": "en",
    "label": "Lithuania",
    "countryPhonePrefix": "370"
  }, {
    "id": 289,
    "code": "EE",
    "nicCode": "543",
    "lang": "ar",
    "label": "استونيا",
    "countryPhonePrefix": "372"
  }, {
    "id": 290,
    "code": "EE",
    "nicCode": "543",
    "lang": "en",
    "label": "Estonia",
    "countryPhonePrefix": "372"
  }, {
    "id": 291,
    "code": "LV",
    "nicCode": "544",
    "lang": "ar",
    "label": "لاتفيا",
    "countryPhonePrefix": "371"
  }, {
    "id": 292,
    "code": "LV",
    "nicCode": "544",
    "lang": "en",
    "label": "Latvia",
    "countryPhonePrefix": "371"
  }, {
    "id": 293,
    "code": "BA",
    "nicCode": "545",
    "lang": "ar",
    "label": "البوسنة والهرسك",
    "countryPhonePrefix": "387"
  }, {
    "id": 294,
    "code": "BA",
    "nicCode": "545",
    "lang": "en",
    "label": "Bosnia / Herzegovina",
    "countryPhonePrefix": "387"
  }, {
    "id": 295,
    "code": "HR",
    "nicCode": "546",
    "lang": "ar",
    "label": "كرواتيا",
    "countryPhonePrefix": "385"
  }, {
    "id": 296,
    "code": "HR",
    "nicCode": "546",
    "lang": "en",
    "label": "Croatia",
    "countryPhonePrefix": "385"
  }, {
    "id": 297,
    "code": "SI",
    "nicCode": "547",
    "lang": "ar",
    "label": "سلوفينيا",
    "countryPhonePrefix": "386"
  }, {
    "id": 298,
    "code": "SI",
    "nicCode": "547",
    "lang": "en",
    "label": "Slovenia",
    "countryPhonePrefix": "386"
  }, {
    "id": 299,
    "code": "MK",
    "nicCode": "549",
    "lang": "ar",
    "label": "مقدونيا",
    "countryPhonePrefix": "389"
  }, {
    "id": 300,
    "code": "MK",
    "nicCode": "549",
    "lang": "en",
    "label": "Macedonia",
    "countryPhonePrefix": "389"
  }, {
    "id": 301,
    "code": "CZ",
    "nicCode": "552",
    "lang": "ar",
    "label": "تشيك",
    "countryPhonePrefix": "420"
  }, {
    "id": 302,
    "code": "CZ",
    "nicCode": "552",
    "lang": "en",
    "label": "Czech Republic",
    "countryPhonePrefix": "420"
  }, {
    "id": 303,
    "code": "SK",
    "nicCode": "553",
    "lang": "ar",
    "label": "سلوفاكيا",
    "countryPhonePrefix": "421"
  }, {
    "id": 304,
    "code": "SK",
    "nicCode": "553",
    "lang": "en",
    "label": "Slovakia",
    "countryPhonePrefix": "421"
  }, {
    "id": 305,
    "code": "FO",
    "nicCode": "554",
    "lang": "ar",
    "label": "جزر فيرو",
    "countryPhonePrefix": "298"
  }, {
    "id": 306,
    "code": "FO",
    "nicCode": "554",
    "lang": "en",
    "label": "Faroe Islands",
    "countryPhonePrefix": "298"
  }, {
    "id": 307,
    "code": "US",
    "nicCode": "601",
    "lang": "ar",
    "label": "الولايات المتحدة",
    "countryPhonePrefix": "1"
  }, {
    "id": 308,
    "code": "US",
    "nicCode": "601",
    "lang": "en",
    "label": "United States",
    "countryPhonePrefix": "1"
  }, {
    "id": 309,
    "code": "AR",
    "nicCode": "602",
    "lang": "ar",
    "label": "الارجنتين",
    "countryPhonePrefix": "54"
  }, {
    "id": 310,
    "code": "AR",
    "nicCode": "602",
    "lang": "en",
    "label": "Argentina",
    "countryPhonePrefix": "54"
  }, {
    "id": 311,
    "code": "BB",
    "nicCode": "603",
    "lang": "ar",
    "label": "بربادوس",
    "countryPhonePrefix": "1-246"
  }, {
    "id": 312,
    "code": "BB",
    "nicCode": "603",
    "lang": "en",
    "label": "Barbados",
    "countryPhonePrefix": "1-246"
  }, {
    "id": 313,
    "code": "BR",
    "nicCode": "604",
    "lang": "ar",
    "label": "البرازيل",
    "countryPhonePrefix": "55"
  }, {
    "id": 314,
    "code": "BR",
    "nicCode": "604",
    "lang": "en",
    "label": "Brazil",
    "countryPhonePrefix": "55"
  }, {
    "id": 315,
    "code": "PA",
    "nicCode": "605",
    "lang": "ar",
    "label": "بنما",
    "countryPhonePrefix": "507"
  }, {
    "id": 316,
    "code": "PA",
    "nicCode": "605",
    "lang": "en",
    "label": "Panama",
    "countryPhonePrefix": "507"
  }, {
    "id": 317,
    "code": "TT",
    "nicCode": "606",
    "lang": "ar",
    "label": "ترينداد وتوباجو",
    "countryPhonePrefix": "1-868"
  }, {
    "id": 318,
    "code": "TT",
    "nicCode": "606",
    "lang": "en",
    "label": "Trinidad and Tobago",
    "countryPhonePrefix": "1-868"
  }, {
    "id": 319,
    "code": "JM",
    "nicCode": "607",
    "lang": "ar",
    "label": "جامايكا",
    "countryPhonePrefix": "1-876"
  }, {
    "id": 320,
    "code": "JM",
    "nicCode": "607",
    "lang": "en",
    "label": "Jamaica",
    "countryPhonePrefix": "1-876"
  }, {
    "id": 321,
    "code": "GY",
    "nicCode": "608",
    "lang": "ar",
    "label": "جوانا",
    "countryPhonePrefix": "592"
  }, {
    "id": 322,
    "code": "GY",
    "nicCode": "608",
    "lang": "en",
    "label": "Joanna",
    "countryPhonePrefix": "592"
  }, {
    "id": 323,
    "code": "VE",
    "nicCode": "609",
    "lang": "ar",
    "label": "فنزويلا",
    "countryPhonePrefix": "58"
  }, {
    "id": 324,
    "code": "VE",
    "nicCode": "609",
    "lang": "en",
    "label": "Venezuela",
    "countryPhonePrefix": "58"
  }, {"id": 325, "code": "CA", "nicCode": "610", "lang": "ar", "label": "كندا", "countryPhonePrefix": "1"}, {
    "id": 326,
    "code": "CA",
    "nicCode": "610",
    "lang": "en",
    "label": "Canada",
    "countryPhonePrefix": "1"
  }, {
    "id": 327,
    "code": "CO",
    "nicCode": "611",
    "lang": "ar",
    "label": "كولمبيا",
    "countryPhonePrefix": "57"
  }, {
    "id": 328,
    "code": "CO",
    "nicCode": "611",
    "lang": "en",
    "label": "Columbia",
    "countryPhonePrefix": "57"
  }, {
    "id": 329,
    "code": "BS",
    "nicCode": "612",
    "lang": "ar",
    "label": "جزر البهاما",
    "countryPhonePrefix": "1-242"
  }, {
    "id": 330,
    "code": "BS",
    "nicCode": "612",
    "lang": "en",
    "label": "Bahamas",
    "countryPhonePrefix": "1-242"
  }, {
    "id": 331,
    "code": "CR",
    "nicCode": "613",
    "lang": "ar",
    "label": "كوستاريكا",
    "countryPhonePrefix": "506"
  }, {
    "id": 332,
    "code": "CR",
    "nicCode": "613",
    "lang": "en",
    "label": "Costa Rica",
    "countryPhonePrefix": "506"
  }, {"id": 333, "code": "CU", "nicCode": "614", "lang": "ar", "label": "كوبا", "countryPhonePrefix": "53"}, {
    "id": 334,
    "code": "CU",
    "nicCode": "614",
    "lang": "en",
    "label": "Cuba",
    "countryPhonePrefix": "53"
  }, {
    "id": 335,
    "code": "DM",
    "nicCode": "615",
    "lang": "ar",
    "label": "دومينيكا",
    "countryPhonePrefix": "1-767"
  }, {
    "id": 336,
    "code": "DM",
    "nicCode": "615",
    "lang": "en",
    "label": "Dominica",
    "countryPhonePrefix": "1-767"
  }, {
    "id": 337,
    "code": "DO",
    "nicCode": "616",
    "lang": "ar",
    "label": "جمهورية دمينكان",
    "countryPhonePrefix": "1-809,1-829,1-849"
  }, {
    "id": 338,
    "code": "DO",
    "nicCode": "616",
    "lang": "en",
    "label": "Republic Dominica",
    "countryPhonePrefix": "1-809,1-829,1-849"
  }, {
    "id": 339,
    "code": "SV",
    "nicCode": "617",
    "lang": "ar",
    "label": "السلفادور",
    "countryPhonePrefix": "503"
  }, {
    "id": 340,
    "code": "SV",
    "nicCode": "617",
    "lang": "en",
    "label": "El Salvador",
    "countryPhonePrefix": "503"
  }, {
    "id": 341,
    "code": "GD",
    "nicCode": "618",
    "lang": "ar",
    "label": "جرانادا",
    "countryPhonePrefix": "1-473"
  }, {
    "id": 342,
    "code": "GD",
    "nicCode": "618",
    "lang": "en",
    "label": "Granada",
    "countryPhonePrefix": "1-473"
  }, {
    "id": 343,
    "code": "GT",
    "nicCode": "619",
    "lang": "ar",
    "label": "جواتيمالا",
    "countryPhonePrefix": "502"
  }, {
    "id": 344,
    "code": "GT",
    "nicCode": "619",
    "lang": "en",
    "label": "Guatemala",
    "countryPhonePrefix": "502"
  }, {
    "id": 345,
    "code": "HT",
    "nicCode": "620",
    "lang": "ar",
    "label": "هايتي",
    "countryPhonePrefix": "509"
  }, {
    "id": 346,
    "code": "HT",
    "nicCode": "620",
    "lang": "en",
    "label": "Haiti",
    "countryPhonePrefix": "509"
  }, {
    "id": 347,
    "code": "HN",
    "nicCode": "621",
    "lang": "ar",
    "label": "هوندوراس",
    "countryPhonePrefix": "504"
  }, {
    "id": 348,
    "code": "HN",
    "nicCode": "621",
    "lang": "en",
    "label": "Honduras",
    "countryPhonePrefix": "504"
  }, {
    "id": 349,
    "code": "MX",
    "nicCode": "622",
    "lang": "ar",
    "label": "المكسيك",
    "countryPhonePrefix": "52"
  }, {
    "id": 350,
    "code": "MX",
    "nicCode": "622",
    "lang": "en",
    "label": "Mexico",
    "countryPhonePrefix": "52"
  }, {
    "id": 351,
    "code": "NI",
    "nicCode": "623",
    "lang": "ar",
    "label": "نيكاراجوا",
    "countryPhonePrefix": "505"
  }, {
    "id": 352,
    "code": "NI",
    "nicCode": "623",
    "lang": "en",
    "label": "Nicaragua",
    "countryPhonePrefix": "505"
  }, {
    "id": 353,
    "code": "LC",
    "nicCode": "624",
    "lang": "ar",
    "label": "سانت لوسيا",
    "countryPhonePrefix": "1-758"
  }, {
    "id": 354,
    "code": "LC",
    "nicCode": "624",
    "lang": "en",
    "label": "Saint Lucia",
    "countryPhonePrefix": "1-758"
  }, {
    "id": 355,
    "code": "VC",
    "nicCode": "625",
    "lang": "ar",
    "label": "سان فينسنت وجزر جرينادين",
    "countryPhonePrefix": "1-784"
  }, {
    "id": 356,
    "code": "VC",
    "nicCode": "625",
    "lang": "en",
    "label": "Saint Vincent",
    "countryPhonePrefix": "1-784"
  }, {
    "id": 357,
    "code": "BO",
    "nicCode": "626",
    "lang": "ar",
    "label": "بوليفيا",
    "countryPhonePrefix": "591"
  }, {
    "id": 358,
    "code": "BO",
    "nicCode": "626",
    "lang": "en",
    "label": "Bolivia",
    "countryPhonePrefix": "591"
  }, {"id": 359, "code": "CL", "nicCode": "627", "lang": "ar", "label": "شيلي", "countryPhonePrefix": "56"}, {
    "id": 360,
    "code": "CL",
    "nicCode": "627",
    "lang": "en",
    "label": "Chile",
    "countryPhonePrefix": "56"
  }, {
    "id": 361,
    "code": "EC",
    "nicCode": "628",
    "lang": "ar",
    "label": "اكوادور",
    "countryPhonePrefix": "593"
  }, {
    "id": 362,
    "code": "EC",
    "nicCode": "628",
    "lang": "en",
    "label": "Ecuador",
    "countryPhonePrefix": "593"
  }, {
    "id": 363,
    "code": "PY",
    "nicCode": "629",
    "lang": "ar",
    "label": "باراجواي",
    "countryPhonePrefix": "595"
  }, {
    "id": 364,
    "code": "PY",
    "nicCode": "629",
    "lang": "en",
    "label": "Paraguay",
    "countryPhonePrefix": "595"
  }, {"id": 365, "code": "PE", "nicCode": "630", "lang": "ar", "label": "بيرو", "countryPhonePrefix": "51"}, {
    "id": 366,
    "code": "PE",
    "nicCode": "630",
    "lang": "en",
    "label": "Peru",
    "countryPhonePrefix": "51"
  }, {
    "id": 367,
    "code": "CC",
    "nicCode": "701",
    "lang": "ar",
    "label": "استراليا",
    "countryPhonePrefix": "61"
  }, {
    "id": 368,
    "code": "CC",
    "nicCode": "701",
    "lang": "en",
    "label": "Australia",
    "countryPhonePrefix": "61"
  }, {
    "id": 369,
    "code": "NZ",
    "nicCode": "702",
    "lang": "ar",
    "label": "نيوزيلندا",
    "countryPhonePrefix": "64"
  }, {"id": 370, "code": "NZ", "nicCode": "702", "lang": "en", "label": "New Zealand", "countryPhonePrefix": "64"}];
  healthSpecialNeeds: Lookup[] = [];
  maritalStatuses: Lookup[] = [{"id": 1, "code": "SINGLE", "lang": "ar", "label": "أعزب"}, {
    "id": 2,
    "code": "SINGLE",
    "lang": "en",
    "label": "Single"
  }, {"id": 3, "code": "MARRIED", "lang": "ar", "label": "متزوج"}, {
    "id": 4,
    "code": "MARRIED",
    "lang": "en",
    "label": "Married"
  }, {"id": 5, "code": "WIDOWED", "lang": "ar", "label": "أرمل"}, {
    "id": 6,
    "code": "WIDOWED",
    "lang": "en",
    "label": "Widowed"
  }, {"id": 7, "code": "DIVORCED", "lang": "ar", "label": "مطلق"}, {
    "id": 8,
    "code": "DIVORCED",
    "lang": "en",
    "label": "Divorced"
  }];
  languageNativeName = Language;

  selectedApplicantRitual: ApplicantRitualLite;

  activeId = 1;
  tabsHeader = [
    "card-management.main_details",
    "card-management.hamlah_details",
    "card-management.health_details",
    "card-management.tafweej_details",
    "card-management.motawef_details"
  ]

  constructor(private route: ActivatedRoute,
              private router: Router,
              private toastr: ToastService,
              private cardService: CardService,
              private translate: TranslateService,
              private i18nService: I18nService,
              private lookupsService: LookupService,
              private userService: UserService
  ) {
  }


  ngOnInit(): void {

    this.userService.selectedApplicantRitual.subscribe(selectedApplicantRitual => {
      this.selectedApplicantRitual = selectedApplicantRitual;
    });

    this.selectedApplicantRitual = JSON.parse(localStorage.getItem('selectedApplicantRitual'));

    this.loadLookups();
    this.cardService.findMainProfile().subscribe(data => {
      if (data) {
        this.applicant = data;
      } else {
        this.toastr.error(this.translate.instant('general.route_item_not_found'),
          this.translate.instant('general.dialog_error_title'));
      }
    });

    this.cardService.findHealthDetails(this.selectedApplicantRitual?.id).subscribe(data => {
      if (data) {
        this.healthDetails = data;
      } else {
        this.toastr.error(this.translate.instant('general.route_item_not_found'),
          this.translate.instant('general.dialog_error_title'));
      }
    });

    //TODO: dummy data
    this.hamlahPackage = {
      "id": 1,
      "typeCode": {"id": 1, "code": null, "label": "VIP", "lang": null},
      "hamlahId": 1,
      "campId": 1,
      "price": 6500,
      "departureCity": "Mombai",
      "countryId": 1,
      "packageHousings": [{
        "id": 1,
        "type": "مزدلفة",
        "code": "25475",
        "labelAr": "مخيم مشاعل النور",
        "labelEn": "",
        "validityStart": "01-04-2021",
        "validityEnd": "02-04-2021",
        "addressAr": "مزدلفة بجوار محطة القطار",
        "addressEn": "",
        "isDefault": true,
        "packageCaterings": [{"id": 1, "type": "غداء", "meal": "", "descriptionAr": "بوفيه مفتوح", "descriptionEn": ""}]
      }],
      "packageTransportations": [{
        "id": 1,
        "type": "باص",
        "validityStart": "03-04-2021",
        "validityEnd": "04-04-2021",
        "locationFrom": "منى",
        "locationTo": "مزدلفة",
        "vehicleNumber": "ب ح ج 259"
      }]
    };
  }

  loadLookups() {
    this.cardService.findRitualTypes().subscribe(result => {
      this.ritualTypes = result;
    });
    this.cardService.findRelativeRelationships().subscribe(result => {
      this.relativeRelationships = result;
    });
    this.cardService.findCountries().subscribe(result => {
      this.countries = result;
    });
    this.cardService.findHealthSpecialNeeds().subscribe(result => {
      this.healthSpecialNeeds = result;
    });
    this.cardService.findMaritalStatuses().subscribe(result => {
      this.maritalStatuses = result;
    });
  }

  // goToList() {
  //   this.router.navigate(['/cards/list']);
  // }

  get currentLanguage(): string {
    return this.i18nService.language;
  }

  lookupService(): LookupService {
    return this.lookupsService;
  }

  packageCaterings(): PackageCatering[] {
    let packageCaterings: PackageCatering[] = [];
    //TODO: to be refactored after wiring the backend to the frontend
    this.hamlahPackage.packageHousings.forEach(housing => {
      packageCaterings = packageCaterings.concat(housing.packageCaterings);
    });
    return packageCaterings;
  }

}
